var keystone = require('keystone');
var Entry = keystone.list('Entry');
var RSS = require('rss');

exports = module.exports = function (req, res) {

	var view = new keystone.View(req, res);
	var locals = res.locals;

	// title : title of your feed
	// link : link to your website
	// desc : description of your feed
	// author : author of the feed
	// feedLink : link to the feed
	// options : additional options, explained below
	var feed = new RSS({
		title: 'Murilo Polese',
		site_url: process.env.SITE_URL,
		feed_url: process.env.SITE_URL + 'blog/feed.xml',
		image_url: 'http://i.imgur.com/WYaVpMS.jpg',
		language: 'en',
		copyright: 'WTFPL',
		generator: 'Generated by murilopolese.com.br',
	});

	Entry.model.find()
		.where({
			type: 'blog',
			status: 'published'
		})
		.sort({createdAt: -1})
		.exec(function(err, entries) {
			if(err) {
				console.log( err );
				view.render('500');
				return;
			}
			if(!entries) {
				view.render('404');
				return;
			}


			entries.forEach(function (entry) {
				feed.item({
					title: entry.title,
					description: entry.blog.brief.html,
					url: process.env.SITE_URL + entry.slug,
					author: 'Murilo Polese',
					date: entry.createdAt,
					enclosure: {
						'url': entry.blog.images[0] || 'http://i.imgur.com/WYaVpMS.jpg'
					}
				});
			});

			var xml = feed.xml({indent: true});

			res.set('Content-Type', 'text/xml');
			res.send( xml );

		});

};
